### ISSUE TITLE
Crash when trying to pick up the backpack.

### ISSUE THREAD

**Issue by Rimevel** [copygirl/WearableBackpacks#107]
Just as the title says. I crash whenever I try to pick up a backpack. Even if it is empty. A crash dump can be found [here](https://paste.dimdev.org/wiwomadimi.mccrash). Maybe it is just me and my modpack, but I thought it was best to post here so you can take a look at it.

**Comment by copygirl** [comment]
Tiny fix. I suppose @asiekierka simply missed replacing this occurence of `null` with `ItemStack.EMPTY` when updating the mod way back. I wonder why this has never been an issue, or reported before...

(Not sure if or when there will be another release?)

**Comment by asiekierka** [comment]
Do you want one to be there now?

**Comment by copygirl** [comment]
@asiekierka It's up to you and @InsomniaKitten.

**Comment by Rimevel** [comment]
Thanks for the fix. Did my own build in the meantime. Everything seem to work great so far. Not a single crash 👍
