### ISSUE TITLE
Duplication glitch

### ISSUE THREAD

**Issue by RedRultra** [copygirl/WearableBackpacks#111]
Hi, I'm experimenting with building a personal modpack centered on magic.
So I installed WB and in my survival test playthrough the first time I died while wearing the backpack and I got back to my death location, all the stuff in the backpack was laying on the floor, but a second copy of everything was stored in the backpack model.

I think this has something to do with compatibility with Corail Tombstone, the grave mod that I'm using.

Anyway I love this mod, thanks for making it in the first place, probably the best balanced backpack mod out there.

**Comment by copygirl** [comment]
Can you reliably reproduce this error with just Wearable Backpacks and Corail Tombstone? I wonder if the other mod attempts to handle backpacks but doesn't do it correctly.

**Comment by RedRultra** [comment]
I tried to reproduce it but it fails every time... it seems like it was a one time thing ... I don't know what was the cause, sorry ... if something happens again then I'll let you know

**Comment by RedRultra** [comment]
Ok so I saw another issue mention the duping happening when you get blown up and tested it, and can confirm that's how my items got duped so since there is now already another issue on this I'll close this one

**Comment by BrokenDoop** [comment]
Yup, still getting this bug. happens every time.
