### ISSUE TITLE
Update forge version

### ISSUE THREAD

**Issue by Xorbah** [copygirl/WearableBackpacks#115]
Can this get an update to a more recent version of forge for 1.12.2? The author of heavy inventories is attempting to add compatibility with your mod but is unable to due to how NBT data is being handled.

**Comment by SuperScary** [comment]
particularly how nbt compounds are checked. example: https://github.com/copygirl/WearableBackpacks/blob/9b542812b766160613386ab676bd1a43d4351468/src/main/java/net/mcft/copy/backpacks/misc/util/NbtUtils.java#L141

newer forge versions use `NBTTagCompound#hasNoTags()`

**Comment by Xorbah** [comment]
Could a developer of the mod please give some feedback?

**Comment by InsomniaKitten** [comment]
This is not a Forge update issue, these are MCP mappings. If you want to use Wearable Backpacks in your workspace you need to use `deobfCompile` on an obfuscated jar to ensure it is mapped correctly for your environment.

**Comment by InsomniaKitten** [comment]
Fwiw, it is whatever environment you are in that is outdated, not ours. Wearable Backpacks was updated to the stable (and final) channel for 1.12 MCP back in September, which made the migration from `hasNoTags` to `isEmpty`: https://github.com/copygirl/WearableBackpacks/commit/141bd8ca14df3cbd01ea9ca173cdb60776095b1c
