### ISSUE TITLE
I want to translate that mod to Turkish language.

### ISSUE THREAD

**Issue by TurkishAhmet4545** [copygirl/WearableBackpacks#129]
Hello.I want to translate that mod to turkish language.What should i do ? 
Note : I know about fork , .lang files etc.

Btw can you give me the translation file as a list ? Because it is very hard to translate it as non-list.I can write somethings wrong.

**Comment by copygirl** [comment]
I'm a little confused. They should be in a list, as seen [here](https://github.com/copygirl/WearableBackpacks/blob/master/src/main/resources/assets/wearablebackpacks/lang/en_us.lang)..? Could it be that you're opening the language file in a text editor that doesn't support unix-style line-breaks? In that case, I would recommend another editor (such as Notepad++ or VS Code) or editing the file directly on github.com.

Keep in mind that I don't know when there will be a next release that will include your changes, though. I'll leave it up to @ChloeDawn (maybe @asiekierka) to make that decision.
