### ISSUE TITLE
Texture rendering issue

### ISSUE THREAD

**Issue by grundyboy34** [copygirl/WearableBackpacks#13]
I've noticed an odd bug that I can't seem to reproduce outside of my world. The skin of the backpack will disappear, but only when looking at it from certain directions, and only when it's at certain locations.

[Image](https://imgur.com/a/NaYoW)

I'm running this on my pack called Immersive Survival, which has many other mods, however this bug doesn't occur on any other world save within the same pack.

**Comment by grundyboy34** [comment]
[Here is two more images that hopefully help.](https://imgur.com/a/EcmXy)

**Comment by copygirl** [comment]
I found the issue happening on my server as well and assume it's another mod causing this issue, though not necessarily its fault. I likely need to just (re)set some rendering related thing.

If you happen to identify which block / tile entity causes the backpack to lose its texture, let me know.

**Comment by grundyboy34** [comment]
I'll play around and see if I can find it. What mods are you running that you think could be causing it? Also if all else fails, we might be able to do something like dump the tile entity/blocks from the chunk via worldedit and compare.

**Comment by grundyboy34** [comment]
[Found it. Storage Drawers with items in them cause it.](https://imgur.com/a/S9HxO)

**Comment by copygirl** [comment]
Awesome! That'll make finding out what I need to do and verifying it so much easier!

**Comment by asiekierka** [comment]
This, in general, is caused by poor OpenGL state upkeep by other mods, and is generally not our fault unless it's *another* mod losing textures. :P
