### ISSUE TITLE
Index out of bounds error

### ISSUE THREAD

**Issue by Sunconure11** [copygirl/WearableBackpacks#134]
https://pastebin.com/UCLqE3Pz

**Comment by copygirl** [comment]
Likely a duplicate of #100. Was the backpack moved with Carry On?

**Comment by Sunconure11** [comment]
Yes. I had since blacklisted this mod from Carry On.

**Comment by copygirl** [comment]
I will close this as a duplicate then. Thank you for reporting it, nonetheless!
