### ISSUE TITLE
Mob's aren't spawning with wearablebackpacks

### ISSUE THREAD

**Issue by GeflGabe** [copygirl/WearableBackpacks#136]
Hello! Apologies for bugging a mod that hasn't been updated in a while, but I have run into a minor yet annoying issue.

I've been tweaking a private personal modpack of mine and after putting this bad boy into my pack, I've stumbled apon the unfortunate issue of no mobs being able to spawn with wearable backpacks. (Which is most of the reason why I installed it >_<)
I tried configing things like chest armor mode on and off, spawner backpacks on and off, and even using the previous version of the mod.
Surely it would be possible in theory for me to just be incredibly unlucky but alas I have set the spawn weight to 1 on different mobs modded and vanilla mobs and it does not seem to be properly giving out backpacks.

My log has been saying the good old  "[Server thread/WARN] [minecraft/WorldServer]: Tried to add entity minecraft:item but it was marked as removed already" a good amount of times,
So I might be able to possibly conclude after my testing that my issue is likely the 1 tick entity removal bug briefly mentioned in [this issue](https://github.com/copygirl/WearableBackpacks/issues/44)

I don't really know why or which mods would or could do this even though I keep strict tabs on all of the mods I use, but I'll give an update that will hopefully help others with this problem if I do find a conflict.

Until then a fix of sorts would be greatly appreciated if possible/out of the way!
Thank you in advance for reading this, and thank you for having great passion and maintenance on this mod!

Edit: Just realized, Happy 3rd birthday to that other issue XD
2nd Edit: Was looking through my configs, couldn't find anything that would get set off by backpacks on mobs, on another note the only hint on this situation I could find online was [this thread from dynamic trees.](https://github.com/ferreusveritas/DynamicTrees/issues/365)

**Comment by copygirl** [comment]
I recently looked into mobs spawning with backpacks and have tested this in a custom modpack of mine, though the particular question was related to setting up additional custom mobs to spawn with backpacks (like cows, creepers, ..). All I can say is that it works for me, and playing the pack normally there has been backpacks dropped from the default mobs that can carry them, too.

The issue might simply be with another mod changing spawning behavior, as I [rely on certain events to fire](https://github.com/copygirl/WearableBackpacks/blob/master/src/main/java/net/mcft/copy/backpacks/ProxyCommon.java#L102). Can you get it working when you test just with Wearable Backpacks? Try disabling a bunch of mods until you notice it starts working again, to get down on which one might be the cause.

**Comment by GeflGabe** [comment]
Alright the cause was useful nulifiers (Have no idea why I hadn't checked that first) I orignally thought it removes redundant or copy items that certain mods add ex. oils, turns out it kinda just causes issues like this rather than improving my fps all that much.

Thank you for the help I was able the cause pretty fast after having what you shared with me in mind.
With that I do have 2 suggestions for an additional feature regarding compatibilties I did actually find (Mobs/npcs from toroquest, mca and tehcguns that use their own spawners) and (Shift right click backpack bind config, since you need shift right click with an empty hand to drink from water blocks in tough as nails), should I make another thread for them?

**Comment by copygirl** [comment]
> Mobs/npcs from toroquest, mca and tehcguns that use their own spawners

If WBs can't put backpacks on them, it may be because those mods don't fire `CheckSpawn` for them. That would be something for them to address.

> Shift right click backpack bind config

Currently the mod is in permafrost. If I were to touch it again or implement a similar feature in a different mod / game, I've already decided that such a feature would be moved to the same key that also accesses the backpack, so I think that would avoid that issue.

Thank you for the suggestions, and I'm glad you found the issue so quickly!
(Though a little confused why that mod causes this problem.)
