### ISSUE TITLE
setting "Equip as Chest Armor" to false, causes backpack to not be able to be picked up.

### ISSUE THREAD

**Issue by EnderLord2468** [copygirl/WearableBackpacks#138]
the mod page says that this feature is for people who don't like the fact that it needs to be equipped as a chestplate, but instead just makes it a bedrock chest rather than a backpack.

**Comment by copygirl** [comment]
Can you break the backpack at all? Usually there would be a chat message as to why the backpack can't be equipped. Did you change this setting in-game, if so, does restarting fix it? Can you verify that the setting was changed in the config file? Can it be equipped if you do have an empty chestplate slot? Does the issue occur with only Wearable Backpacks installed?

**Comment by EnderLord2468** [comment]
oh wait there was no bug, I just misunderstood how this option worked. this modpack i was playing on made the backpack really quiet so I didn't know I was breaking it, and thought that when i shift left clicked with the option turned off the backpack would just disappear until I right clicked, so I never tried to click somewhere else for fear of deleting it, so sorry for wasting your time with this.

**Comment by copygirl** [comment]
Alright, I'm glad it's working for you!
