### ISSUE TITLE
[suggestion]

### ISSUE THREAD

**Issue by SarahCarrot** [copygirl/WearableBackpacks#139]
Baubles compatibility? I think it would be nice so you still get the effect of wearing a backpack while still being able to wear armor.

**Comment by copygirl** [comment]
Closing as duplicate of #52. (Note: Development of this mod is stopped.)

It would be nice to have, though there is the config option `equipAsChestplate` which can be turned off to wear backpacks (in a sort of "invisible" slot) without taking up the armor slot.
