### ISSUE TITLE
Is there a way to change the mod so that I can give access to a players inventory slots as well?

### ISSUE THREAD

**Issue by Vivigar** [copygirl/WearableBackpacks#142]
I am wanting to make the inventory limited as just a few inventory slots until a player has a backpack in a modpack. Afterwards instead of adding additional inventory, I'd like it to just unluck the main inventory as the backpack's inventory and still be accessible by other players. Is there I can make this happen using another mod TinyInv? https://www.curseforge.com/minecraft/mc-mods/tinyinv

**Comment by copygirl** [comment]
Possible, but it would require modifications to both mods, or ideally merging both into one. Not an easy task, considering all the assumptions that Wearable Backpacks was written under.

I will close this, as this is definitely not in the scope of this repository.
