### ISSUE TITLE
Corrputing playerdata

### ISSUE THREAD

**Issue by Cummo** [copygirl/WearableBackpacks#144]
I was hosting a server with my friend and was asking for help because it did not allow us to join because of a code but they believed that was caused by the mod.  Our playerdata to got corrupted. We where adjusting the config. to make the backpacks openable by players and able to be worn with chestplates. Then the issue occured
![RLCraft 7_28_2022 2_43_45 PM](https://user-images.githubusercontent.com/110350735/182039825-d0808afb-4838-49ab-a164-b9895c06c95e.png)

https://paste.gg/p/anonymous/1b523c6296354e05843b2d01c88765d7

**Comment by copygirl** [comment]
I checked the log but could not find anything that would indicate WearableBackpack being at fault.

When looking for the error, I can find EnigmaticaModpacks/Enigmatica2Expert#1592. Have a look through that and see if any of the suggested fixes work for you. As this is unlikely to actually be an issue with my mod, I'll close this issue for now. I'll still respond to any comments if I can help with anything, though.
