### ISSUE TITLE
I don’t know how to download this mod

### ISSUE THREAD

**Issue by Njkiech** [copygirl/WearableBackpacks#151]

**Comment by copygirl** [comment]
You can get the .jar file from either [this repo's releases page](https://github.com/copygirl/WearableBackpacks/releases) or the [CurseForge page](https://www.curseforge.com/minecraft/mc-mods/wearable-backpacks). If you use a launcher that can install mods from CurseForge, use that. Note that WBs requires Forge and is only updated to 1.12.2, which is very outdated.
