### ISSUE TITLE
Backpack stuck on back

### ISSUE THREAD

**Issue by saltypatt** [copygirl/WearableBackpacks#152]
When I broke the backpack on the ground, it instantly re-equipped and I cannot take the backpack off at all, please help :,)

**Comment by copygirl** [comment]
Sneaking when breaking the backpack block equips it. Sneak and right click the ground with an empty hand unequips it. Alternatively, you can also die, and the backpack will drop (unless `keepInventory` is turned on). The backpack can not be unequipped through normal means.

(I also released a custom version for a modpack that changes the controls for placing to sneak + `B`, in case you happen to use that version.)
