### ISSUE TITLE
java.lang.NoSuchFieldError: _entry

### ISSUE THREAD

**Issue by Fuzzbling** [copygirl/WearableBackpacks#25]
Crash Report:
[https://gist.github.com/Fuzzbling/0b2c7872a4c924aaf1224729315741d0](https://gist.github.com/Fuzzbling/0b2c7872a4c924aaf1224729315741d0)

**Comment by copygirl** [comment]
That's what I get for not testing properly. Yay.
Will fix tomorrow, as I'm already getting ready for sleep.

From a quick glance, this should only happen on the server..? Perhaps a default initializer doesn't work well with `SideOnly`...

**Comment by Fuzzbling** [comment]
While I'm no mod dev, I did find the following that might be helpful in troubleshooting this;
https://mcforge.readthedocs.io/en/latest/concepts/sides/
https://github.com/MinecraftForge/MinecraftForge/issues/3066
https://github.com/minecraft-dev/MinecraftDev/issues/28

There were quite a few other results using this search:
https://www.google.com/search?q=%40SideOnly(Side.CLIENT)

**Comment by copygirl** [comment]
I tried fixing it on my laptop but unfortunately I can't setup a development environment. Apparently decompiling Minecraft takes 3 GB of ram. I'm relatively sure about the cause and reason. It's just slightly weird that it acts this way. I'd assume `@SideOnly` on an initialized field would not cause it to be initialized, but that's alright. (I just have to get rid of the `= null`.)

Meanwhile, I guess I should remove the releases, as they're faulty.
