### ISSUE TITLE
Client startup crash with 2.4.0

### ISSUE THREAD

**Issue by Vazkii** [copygirl/WearableBackpacks#28]
it's borked

https://gist.github.com/Vazkii/15286ab2f2ac3268be28b357fe1c8f30#file-gistfile1-txt-L334

**Comment by copygirl** [comment]
I'm seriously frustrated by Forge and Gradle at this point.
Is `./gradlew --refresh-dependencies setupDecompWorkspace build` still not enough?

**Comment by copygirl** [comment]
Fixed with [2.4.1 release](https://github.com/copygirl/WearableBackpacks/releases/tag/v2.4.1).

**Comment by Vazkii** [comment]
thank coppi
