### ISSUE TITLE
NPE on world join

### ISSUE THREAD

**Issue by yrsegal** [copygirl/WearableBackpacks#29]
https://github.com/copygirl/WearableBackpacks/blob/master/src/main/java/net/mcft/copy/backpacks/ProxyCommon.java#L188

Not much more info in the crashlog, it is an NPE after all.

**Comment by copygirl** [comment]
I would still like to see the crash log. It includes loaded mods, versions and the stack trace, which can all be useful.

**Comment by copygirl** [comment]
I could imagine a fake player with no inventory is causing this issue, but I'd like to verify.

**Comment by copygirl** [comment]
Closing the issue for now. Theoretically I identified the issue but I would still like to know more. Please reopen if you can provide the missing information, @yrsegal.
