### ISSUE TITLE
[1.12] crash on startup

### ISSUE THREAD

**Issue by Seth0067** [copygirl/WearableBackpacks#34]
[Crash report](https://pastebin.com/umaR8Tp5)

Cheers!

**Comment by copygirl** [comment]
Wait.. really? Again? Fuck my life.

**Comment by copygirl** [comment]
Fixed with [version 3.0.2](https://github.com/copygirl/WearableBackpacks/releases/tag/v3.0.2). Thanks for letting me know.

**Comment by Seth0067** [comment]
Anytime - thanks for the update!
