### ISSUE TITLE
[1.12] Backpack not showing in JEI in survival

### ISSUE THREAD

**Issue by donqixot** [copygirl/WearableBackpacks#38]
Thank you for this mod! Really cool!
Using latest forge 14.21.1.2387 and JEI 1.12-4.7.0.68, I can't find wearable backpack in recipe list in survival mode. Strangely enough, I can see it in creative and pressing R for recipe shows the recipe! I can even make it in survival, just not visible in JEI.

**Comment by donqixot** [comment]
Apologies, my mistake, all good and visible in JEI, it was texture interference from another mod.

**Comment by copygirl** [comment]
No problem at all. If you do find any issues please let me know. I haven't had much chance to test WB for 1.12.
