### ISSUE TITLE
Not able to craft the backpack

### ISSUE THREAD

**Issue by lellissa** [copygirl/WearableBackpacks#40]
Hey!
I play on 1.12 with Forge 14.21.0.2331 and the 3.0.2 version of this mod (I tried the 3.0.0 too), but I can`t craft the backpack. When I put all the ingridients in to the craft table nothing happens.
When I exit the world I can see that the mod is loaded and I can configure it.  
Other mods I use: Optifine, Ruins, XaerosMinimap and Worldmap.
If you need any other information I will be happy to provide it!

PS: I have to use this version of Forge, because its the only one Optifine supports right now for 1.12

**Comment by copygirl** [comment]
This specific version of Forge might not have working recipes. Even if there was a way to fix this on Wearable Backpacks' end, it would be a little silly to support an outdated, unsupported and unfinished beta version of Forge for 1.12. Apologies.

**Comment by copygirl** [comment]
For the record, [here it the changelog for Forge 2344](http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12-14.21.0.2344/forge-1.12-14.21.0.2344-changelog.txt), the version WB 3.0.2 was built for. As you can see between 2331 and 2344 there were a bunch of fixes and changes regarding the recipe system.
