### ISSUE TITLE
Weird incompatibility with Nature's Compass mod

### ISSUE THREAD

**Issue by DarkPandaX** [copygirl/WearableBackpacks#43]
I've also submitted this issue to the GitHub for Nature's Compass.

When using both mods together in 1.12, upon making the Nature's Compass, it was a gray wearable backpack, and not the compass. It's such a bizarre conflict of mods that I'm not sure why the hell it would do this, so I figure perhaps there's something going on with one of the mods that should be looked into.
![2017-07-23_19 03 18](https://user-images.githubusercontent.com/30394830/28503770-95dcdf5c-6fda-11e7-9d59-4c3a35890c53.png)
![2017-07-23_19 03 29](https://user-images.githubusercontent.com/30394830/28503774-9eb580b6-6fda-11e7-8072-d88489a7e37c.png)

**Comment by copygirl** [comment]
There was an [issue with item models](https://github.com/copygirl/WearableBackpacks/issues/42) that should have been fixed in the [latest release](https://github.com/copygirl/WearableBackpacks/releases/tag/v3.0.4).
Are you using 3.0.3 or 3.0.4?

**Comment by copygirl** [comment]
Linking to other issue: MattCzyr/NaturesCompass#5

**Comment by MattCzyr** [comment]
As far as I can tell, this is just an issue on my end. Will be fixed with a new Nature's Compass release in the next couple days.

**Comment by copygirl** [comment]
@MattCzyr: Cool. Feel free to look into the issue I mentioned above in case you made the same mistake as me. PaleoCrafter has described the problem pretty well.

**Comment by copygirl** [comment]
Closing since it's an issue with Nature's Compass and being fixed anyway.
