### ISSUE TITLE
Crash wearable 1.12-3.0.4 Forge 14.21.1.2426

### ISSUE THREAD

**Issue by poboy975** [copygirl/WearableBackpacks#44]
Hi, I keep getting random crashes to desktop. Crash report says backpacks is the issue. Wasn't even wearing the backpack at the time, it was in my refined storage system.
[crash-2017-07-28_22.54.37-server.txt](https://github.com/copygirl/WearableBackpacks/files/1185106/crash-2017-07-28_22.54.37-server.txt)

**Comment by copygirl** [comment]
I actually saw the bug earlier today on the Minecraft Forums (I totally don't google for "Wearable Backpacks" every few days). This is not good. I'll check it, soon.

**Comment by copygirl** [comment]
What is the `backpack.durability` setting set to?

**Comment by copygirl** [comment]
I've tried a couple of things and can't reproduce this at the moment. The issue arises from mobs randomly spawning with backpacks, and, for some reason, they appear to spawn incorrectly or in an invalid state. Not sure if it's a just rare circumstances or something caused by the presence of another mod.

Can you download [this test version](https://drive.google.com/file/d/0ByaJlPeqIEMhSHV2SzRmNlo3Y00)? It will remove the randomness and spawn any zombie or skeleton with a backpack. (I suggest doing this in a new world. Just fly around a bunch in creative to cause mobs to spawn/despawn.) Does changing Wearable Backpacks' config settings fix the issue? Do you run into the issue without any other mods installed? If your answer to both is no, may I ask you to test this until you find the mod that's causing the issue?

**Comment by poboy975** [comment]
Ok, I'll give the test version a try. Made a copy of my world, I'll fly around and see if it crashes. I'll try flying around for a while, and changing the backpack durability setting. I'm pretty sure I had it set pretty high if not all the way up.

**Comment by copygirl** [comment]
Ooohhh... I see. So somehow between the entity spawning and the first update tick, the backpack was removed..? That's... odd. Can you think of any mod that would do this, out of curiosity? Let me know if you run into this issue at all while flying around. If not, I will wait for the next bigger update to release the fix.

**Comment by poboy975** [comment]
ok, flew around in creative mode, with a backpack on. I a world copy with all the same mods and your testing version. No crashing after 10 minutes. Quit and restarted my survival world, about 1 minute after logging into the world, after things finished updated and lag settled down, I turned around and crashed. Didn't even have much of a chance to change anything. I don't seem to crash anywhere except for in my base, I might have too many machines running nearby, ore processing, mob farms etc...

[crash-2017-07-30_16.01.13-server.txt](https://github.com/copygirl/WearableBackpacks/files/1185981/crash-2017-07-30_16.01.13-server.txt)

**Comment by copygirl** [comment]
I suppose I could force a fix though I do not understand the cause. I don't like those kinds of "fixes", so I'll probably hold out on it and see if anyone runs into the same issue so I can get more insight. Though there's one important question I have: Is the `equipAsChestArmor` setting on or off?

For now I would recommend to just remove Wearable Backpacks, hoping it's not too important at the moment.

**Comment by poboy975** [comment]
It was set to equipAsChestArmor on. With 214000 durability and max armor. I've turned off the chest armor for this attempt, and am starting my game now.

**Comment by poboy975** [comment]
Still crashed. It's ok, I can remove the mod. I do love the backback, but I can work around it for now. Here is my latest crash report.
[crash-2017-07-30_16.25.00-server.txt](https://github.com/copygirl/WearableBackpacks/files/1185992/crash-2017-07-30_16.25.00-server.txt)

**Comment by copygirl** [comment]
Next time you use it, you can set the durability to `0` for it to last forever. (Just don't change it once a backpack is already partially damaged, the game will treat it as broken / non-existent then.)

**Comment by asiekierka** [comment]
I'm pretty sure durability should be within the 0..32766 range, or so. To be safe, I made the maximum durability 32000 in the latest update.
