### ISSUE TITLE
[Resource] es_MX / es_ES translation

### ISSUE THREAD

**Issue by Dorzar** [copygirl/WearableBackpacks#45]
//Translate by: Dorzar / VeryHardChamp
//Act.: 30/07/2017
container.wearablebackpacks.backpack=Mochila

item.wearablebackpacks.backpack.name=Mochila

tooltip.wearablebackpacks.moreInfo=Presiona %1$s para más información.
tooltip.wearablebackpacks.openHint=Presiona %1$s para abrir la mochila teniéndola equipada.
tooltip.wearablebackpacks.equipHint=Equipar mochila: SHIFT + rómperla.
tooltip.wearablebackpacks.equipHint.extended=Equipar mochila: SHIFT + rómperla.\nDesequipar mochila: SHIFT + clic derecho en el suelo con la mano vacia.
tooltip.wearablebackpacks.unequipHint=Desequipar mochila: SHIFT + clic derecho en el suelo con la\nmano vacia.
tooltip.wearablebackpacks.used=Actualmente está siendo utilizada por un jugador.

chat.wearablebackpacks.cantEquip=Ya tienes una mochila equipada.
chat.wearablebackpacks.cantEquip.chestplate=No puedes equiparte una mochila mientras llevas una pechera.

key.wearablebackpacks.open=Abrir mochila

config.wearablebackpacks.general.equipAsChestArmor=Equip as Chest Armor
config.wearablebackpacks.general.equipAsChestArmor.tooltip=Controls whether equipped backpacks take up the chest armor equipment slot
config.wearablebackpacks.general.enableEquippedInteraction=Enable Equipped Interaction
config.wearablebackpacks.general.enableEquippedInteraction.tooltip=Controls whether players can access equipped backpacks on other players (and entities)
config.wearablebackpacks.general.enableSelfInteraction=Enable Self Interaction
config.wearablebackpacks.general.enableSelfInteraction.tooltip=Controls whether players can access their own equipped backpack using a keybind
config.wearablebackpacks.general.dropAsBlockOnDeath=Drop as Block on Death
config.wearablebackpacks.general.dropAsBlockOnDeath.tooltip=Controls whether backpacks place themselves down upon death, instead of scattering their contents

config.wearablebackpacks.category.backpack=Backpack Settings
config.wearablebackpacks.category.backpack.tooltip=Controls settings regarding regular backpacks
config.wearablebackpacks.backpack.enabled=Enabled
config.wearablebackpacks.backpack.enabled.tooltip=Controls whether the regular backpack is enabled
config.wearablebackpacks.backpack.durability=Durability
config.wearablebackpacks.backpack.durability.tooltip=Controls the durability of the regular backpack (0 for unbreakable). Lowering this (including setting to 0) can cause issues with already damaged backpacks
config.wearablebackpacks.backpack.durability.hint=No effect if not equipped as armor
config.wearablebackpacks.backpack.armor=Armor
config.wearablebackpacks.backpack.armor.tooltip=Armor points of regular backpacks.
config.wearablebackpacks.backpack.armor.hint=No effect if not equipped as armor
config.wearablebackpacks.backpack.size=Storage Size
config.wearablebackpacks.backpack.size.tooltip=Controls the storage size of regular backpacks. Does not affect placed or equipped backpacks

config.wearablebackpacks.category.cosmetic=Cosmetic Settings
config.wearablebackpacks.category.cosmetic.tooltip=Controls cosmetic (client only) settings that don't affect gameplay
config.wearablebackpacks.cosmetic.enchantEffectOpacity=Enchant Effect Opacity
config.wearablebackpacks.cosmetic.enchantEffectOpacity.tooltip=Controls the opacity / visibility of the enchantment effect on equipped and placed backpacks, if present.

**Comment by copygirl** [comment]
Can you create a pull request for this? To do this, go [here](https://github.com/copygirl/WearableBackpacks/tree/master/src/main/resources/assets/wearablebackpacks/lang) and click "Create new file". Copy over the contents of [en_US.lang](https://github.com/copygirl/WearableBackpacks/blob/master/src/main/resources/assets/wearablebackpacks/lang/en_US.lang) and put `"# "` in front of every line that you aren't translating (like [here](https://github.com/copygirl/WearableBackpacks/blob/master/src/main/resources/assets/wearablebackpacks/lang/de_DE.lang#L40)). Then submit your changes as a pull request. (I believe GitHub should somewhat guide you through this.) This is both to make things easier for me and be able to properly keep track of your contribution.

Thanks! :heart:

**Comment by Dorzar** [comment]
Sure!
[https://github.com/copygirl/WearableBackpacks/compare/master...Dorzar:patch-1#diff-caa9b989f649cb97d97a8e4ef590bfaf]Enjoy it

**Comment by copygirl** [comment]
I'd still like for you to actually submit the pull request.

**Comment by Dorzar** [comment]
Ejoy it again? xd
https://github.com/copygirl/WearableBackpacks/pull/46
