### ISSUE TITLE
Mobs spawned from spawners spawn with backpacks

### ISSUE THREAD

**Issue by copygirl** [copygirl/WearableBackpacks#47]
Could leave this option in as a config setting.

**Comment by charliedown** [comment]
Hello copygirl. First congrats your excellent, amazing work with this necessary mod, that I think should come inside vanilla minecraft.
Second to say: I test your 1.12 3.0.4 44 test file, but almost all mobs are using the backpacks. If it possible put the option to disable mobs spawning with the backpacks. 

Thank you very much.

**Comment by copygirl** [comment]
@charliedown Thank you!

And, *obviously*, [the test file from issue #44](https://github.com/copygirl/WearableBackpacks/issues/44#issuecomment-318923458) has spawn chances set to 100% (for supported mobs) to test the crash issue `:P`. I don't think there's any other changes in that version compared to the official 3.0.4 release, so you're not missing out.

The next version of the mod will not only have the option to disable backpacks spawning on mobs using a single button but to completely adjust the chances (and more) *and* add support for more in-built and custom mobs!
