### ISSUE TITLE
Suggestion: Add Backpack size to NBT data

### ISSUE THREAD

**Issue by ulkunderscore** [copygirl/WearableBackpacks#48]
What I mean is to allow NBT data to determine (or modify) the inventory size with rows and columns like in the config.

My goal was to have an extra column backpack only from dungeon loot, but coming to think of it it would also make the mod more versatile for progression-based modpacks.

**Comment by copygirl** [comment]
From the readme:

> ### For Modpack / Map Creators
>
>    Custom backpack size can be set using NBT tag `backpack:{size:[x,y]}`.
>    Custom armor value can be set using NBT `tag backpack:{armor:x}`.
>    Default backpack loot table `wearablebackpacks:backpack/default` can be overridden.

Is this what you meant?

**Comment by ulkunderscore** [comment]
That's exactly what I meant, good stuff.
My bad for missing that.

**Comment by copygirl** [comment]
No worries. Happens to everyone :)
