### ISSUE TITLE
Cross-mod problem with Dr Cyanos' Lootable Bodies

### ISSUE THREAD

**Issue by Sninctbur** [copygirl/WearableBackpacks#73]
[Dr. Cyanos' Lootable Bodies](https://minecraft.curseforge.com/projects/drcyanos-lootable-bodies?gameCategorySlug=mc-mods&projectID=240968)
With "Drop as Block on Death" enabled, the backpack will spawn next to the corpse, but a duplicated backpack will be in the corpse's inventory.

With it disabled, the items in the backpack can be destroyed if their inventory doesn't have enough room for its contents.

**Comment by asiekierka** [comment]
This doesn't seem to be a problem in the latest version. If it re-occurs, please reproduce with 3.1.3.
