### ISSUE TITLE
getIsRepairable doesn't handle getting empty stacks

### ISSUE THREAD

**Issue by DaedalusGame** [copygirl/WearableBackpacks#75]
you directly call getOreIDs which will throw an exception if the stack is empty
this isn't a big deal, and i can fix this problem on my end just wanted to check with you
other than that, backpacks also don't return a proper repair material stack (which is basicly how this got tangled in my code to begin with)

EDIT: I resolved this on my end but maybe this still deserves looking at, poorly implemented repair machines could crash badly, idk.

**Comment by copygirl** [comment]
I have mixed feelings about `getIsRepeairable` having to account for empty stacks. Like, why would you call it with an empty stack in the first case? Then, on the other hand, empty stacks are supposed to make things less painful and crashy.

I don't have a dev environment so I can't check and say anything about the repair material stack thing. WBs is shelved for me right now, so not sure if I'll get to work on this issue.

**Comment by asiekierka** [comment]
Poorly implemented repair machines should become less poorly implemented. We shouldn't hide issues.

**Comment by DaedalusGame** [comment]
i mean, fair enough, but would you expect that passing the repair item from the item into its isRepairable method crashes the game?

**Comment by copygirl** [comment]
If the repair item is an empty stack (or null?), you already know it's not repairable. Why would you call anything on top of that?

**Comment by asiekierka** [comment]
Oh, *we* return an empty stack? We should probably kind of cover that, then.

**Comment by copygirl** [comment]
> Oh, we return an empty stack? We should probably kind of cover that, then.

It's the default behavior for `Item`.
