### ISSUE TITLE
game crashes while loading

### ISSUE THREAD

**Issue by y0rc** [copygirl/WearableBackpacks#85]
Good day,

I am using the Forge Profile Version 1.12.2-14.23.2.2611 and some Mods especially the Wearable Backpacks Mod Version 1.12.2-3.1.3. But my game crashes everytime, when Forge is loading the Backpack Mod. When I delete this mod from my mods folder everything is fine - no crashes. Maybe there are some Mods that are not compatible with this one?

crash report:
---- Minecraft Crash Report ----

WARNING: coremods are present:
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  OpenModsCorePlugin (OpenModsLib-1.12.2-0.11.5.jar)
  TransformerLoader (OpenComputers-MC1.12.2-1.7.2.67.jar)
Contact their authors BEFORE contacting forge

// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 7/28/18 4:57 PM
Description: Initializing game

java.lang.NoSuchMethodError: net.minecraftforge.fml.common.registry.GameRegistry.registerTileEntity(Ljava/lang/Class;Lnet/minecraft/util/ResourceLocation;)V
	at net.mcft.copy.backpacks.BackpacksContent.onRegisterBlocks(BackpacksContent.java:35)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_310_BackpacksContent_onRegisterBlocks_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:143)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:734)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:604)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:270)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.mcft.copy.backpacks.BackpacksContent.onRegisterBlocks(BackpacksContent.java:35)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_310_BackpacksContent_onRegisterBlocks_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:143)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:734)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:604)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:270)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 241190152 bytes (230 MB) / 570425344 bytes (544 MB) up to 1073741824 bytes (1024 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.2.2611 27 mods loaded, 27 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                  | Version                  | Source                                          | Signature                                |
	|:----- |:------------------- |:------------------------ |:----------------------------------------------- |:---------------------------------------- |
	| UCH   | minecraft           | 1.12.2                   | minecraft.jar                                   | None                                     |
	| UCH   | mcp                 | 9.42                     | minecraft.jar                                   | None                                     |
	| UCH   | FML                 | 8.0.99.99                | forge-1.12.2-14.23.2.2611.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge               | 14.23.2.2611             | forge-1.12.2-14.23.2.2611.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | openmodscore        | 0.11.5                   | minecraft.jar                                   | None                                     |
	| UCH   | opencomputers|core  | 1.7.2.67                 | minecraft.jar                                   | None                                     |
	| UCH   | mercurius_updater   | 1.0                      | MercuriusUpdater-1.12.2.jar                     | None                                     |
	| UCH   | betterbuilderswands | 0.11.1                   | BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar | None                                     |
	| UCH   | elevatorid          | 1.3.6                    | ElevatorMod-1.12.2-1.3.6.jar                    | None                                     |
	| UCH   | jei                 | 4.11.0.202               | jei_1.12.2-4.11.0.202.jar                       | None                                     |
	| UCH   | mantle              | 1.12-1.3.2.24            | Mantle-1.12-1.3.2.24.jar                        | None                                     |
	| UCH   | tconstruct          | 1.12.2-2.10.1.87         | TConstruct-1.12.2-2.10.1.87.jar                 | None                                     |
	| UCH   | extrautils2         | 1.0                      | extrautils2-1.12-1.8.1.jar                      | None                                     |
	| UCH   | familiarfauna       | 1.0.10                   | FamiliarFauna-1.12.2-1.0.10.jar                 | None                                     |
	| UCH   | ichunutil           | 7.1.4                    | iChunUtil-1.12.2-7.1.4.jar                      | None                                     |
	| UCH   | inventorytweaks     | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                        | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCH   | ironbackpacks       | 1.12.2-3.0.8-12          | IronBackpacks-1.12.2-3.0.8-12.jar               | None                                     |
	| UCH   | ironchest           | 1.12.2-7.0.40.824        | ironchest-1.12.2-7.0.40.824.jar                 | None                                     |
	| UCH   | journeymap          | 1.12.2-5.5.2             | journeymap-1.12.2-5.5.2.jar                     | None                                     |
	| UCH   | llor                | 1.1.6-mc1.12.2           | LLOverlayReloaded-1.1.6-mc1.12.2.jar            | None                                     |
	| UCH   | morph               | 7.1.2                    | Morph-1.12.2-7.1.2.jar                          | None                                     |
	| UCH   | openmods            | 0.11.5                   | OpenModsLib-1.12.2-0.11.5.jar                   | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| UCH   | openblocks          | 1.7.6                    | OpenBlocks-1.12.2-1.7.6.jar                     | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| UCH   | opencomputers       | 1.7.2.67                 | OpenComputers-MC1.12.2-1.7.2.67.jar             | None                                     |
	| UCH   | oreberries          | 0.5.0                    | oreberries-1.12.x-0.5.0.jar                     | None                                     |
	| UCH   | wearablebackpacks   | 3.1.3                    | WearableBackpacks-1.12.2-3.1.3.jar              | None                                     |
	| UCH   | worldedit           | 6.1.8                    | worldedit-forge-mc1.12-6.1.8-dist.jar           | None                                     |

	Loaded coremods (and transformers): 
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
OpenModsCorePlugin (OpenModsLib-1.12.2-0.11.5.jar)
  openmods.core.OpenModsClassTransformer
TransformerLoader (OpenComputers-MC1.12.2-1.7.2.67.jar)
  li.cil.oc.common.asm.ClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 388.13' Renderer: 'GeForce GTX 960/PCIe/SSE2'
	OpenModsLib class transformers: [llama_null_fix:FINISHED],[horse_base_null_fix:FINISHED],[pre_world_render_hook:FINISHED],[player_render_hook:FINISHED],[horse_null_fix:FINISHED]
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)

	Launched Version: 1.12.2-forge1.12.2-14.23.2.2611
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 960/PCIe/SSE2 GL version 4.6.0 NVIDIA 388.13, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-6600 CPU @ 3.30GHz

hope I did everything right with the crash report and stuff ..
hope someone could help me. I guess there is a really simple solution for this.

Have a nice day ~

**Comment by asiekierka** [comment]
That version of Forge is ancient. You should update it.
