### ISSUE TITLE
Dupe bug on explosion

### ISSUE THREAD

**Issue by PaperTriangle** [copygirl/WearableBackpacks#86]
In the latest 3.1.3 version an explosion that kills the player causes both the backpack to place a block containing its inventory, as well as drop the backpack and all of its content as items. Effectively doubling the backpack inventory.

I tested this on both 3.1.3 and 3.1.2, clean forge install with only Wearable Backpacks installed. Could not get bug to occur on 3.1.2.

**Comment by copygirl** [comment]
Confirmed once more by #111.

**Comment by Laike-Endaril** [comment]
I can also confirm this; just tested it on 3.1.3 and 3.1.2, and it is as the OP said.  I'll be using 3.1.2 for now.
