### ISSUE TITLE
Inventory Tweaks

### ISSUE THREAD

**Issue by Leeo97one** [copygirl/WearableBackpacks#9]
We currently can't use Inventory Tweaks in the backpacks' inventory so I've configured some compatibility informations in the file `config/InvTweaksCompatibility.xml`:
```xml
<root>
   <chest class="net.mcft.copy.backpacks.container.ContainerBackpack" row_size="4" large_chest="false"/>
</root>
```
And it works!
But it would be better if you could use the [Inventory Tweaks API](http://inventory-tweaks.readthedocs.io/en/latest/#download) for an out the box compatibility.

**Comment by copygirl** [comment]
Inventory Tweaks always comes back to haunt me, whether it is as a player or as a mod developer.

Thanks for providing information on how to add compatibility as player / modpack author. I'll see if I can get this added some time. Welcoming PRs for this as well!
