### ISSUE TITLE
Mo' Bends compat

### ISSUE THREAD

**Issue by Zahkriiven** [copygirl/WearableBackpacks#98]
Hello, I saw that in the last update there was a fix https://github.com/copygirl/WearableBackpacks/pull/82 to make mo' bends compatible but I still cant see them work together. Sorry if i am missing something here as I see it working in the gif.

As seen on the image the backpack equipped as chestplate gives armor but it's not rendered
![2018-10-08_23 07 52](https://user-images.githubusercontent.com/25531677/46633841-37927480-cb4f-11e8-8e65-774a1c1ecbb3.png)

Mods:
WearableBackpacks-1.12.2-3.1.3
Mobends-0.24

**Comment by Zahkriiven** [comment]
Looks like it works in Mo' Bends 0.25 test builds that are not in curse.

**Comment by copygirl** [comment]
Ah that's awesome. I thought I remembered there being something done on Mo' Bends' end for compatibility with this mod.
